services:
  core:
    build:
      context: ./core
    container_name: core_service
    ports:
      - "8000:8000"
    environment:
      QDRANT_URL: "http://qdrant_service:6333"
      NGROK_API_KEY: "${NGROK_API_KEY}"
      OPENAI_API_URL: "${OPENAI_API_URL}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      OPENAI_MODEL_NAME: "${OPENAI_MODEL_NAME}"
    depends_on:
      - qdrant

  ui:
    build:
      context: ./ui
    container_name: ui_service
    ports:
      - "8501:8501"
    environment:
      OPENAI_API_URL: "http://core_service:8000"
      OPENAI_API_KEY: "cg_123456789_key"
      PGHOST: "${PGHOST}"
      PGDATABASE: "${PGDATABASE}"
      PGUSER: "${PGUSER}"
      PGPASSWORD": "${PGPASSWORD}"
    depends_on:
      - core

  qdrant:
    image: qdrant/qdrant:v1.11.3
    container_name: qdrant_service
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
