services:
  core:
    build:
      context: ./core
    container_name: core_service
    ports:
      - "8000:8000"
    environment:
      QDRANT_URL: "http://qdrant_service:6333"
      NGROK_API_KEY: "${NGROK_API_KEY}"
      OPENAI_API_URL: "${OPENAI_API_URL}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      OPENAI_MODEL_NAME: "${OPENAI_MODEL_NAME}"
    depends_on:
      - qdrant
      - postgres  

  ui:
    build:
      context: ./ui
    container_name: ui_service
    ports:
      - "8501:8501"
    environment:
      OPENAI_API_URL: "http://core_service:8000"
      OPENAI_API_KEY: "cg_123456789_key"
      PGHOST: "postgres_service"
      PGDATABASE: "cgourmetfb"
      PGUSER: "cgourmet_user"
      PGPASSWORD: "P@ssw0rd2024"
    depends_on:
      - core

  qdrant:
    image: qdrant/qdrant:v1.11.3
    container_name: qdrant_service
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  postgres:
    image: postgres:16
    container_name: postgres_service
    environment:
      POSTGRES_DB: "cgourmetfb"
      POSTGRES_USER: "cgourmet_user"
      POSTGRES_PASSWORD: "P@ssw0rd2024"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: