[project]
name = "vector-db"
version = "0.1.0"
description = "used to prepare vector database"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets==3.0.0",
    "polars==1.7.1",
    "qdrant-client[fastembed]>=1.11.3",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.6.8",
]
